- libs/types/src/lib/api/Country/country.view.ts
- libs/types/src/lib/api/Country/index.ts
- libs/types/src/lib/api/Media/media.view.ts
- libs/types/src/lib/api/index.ts
dev-registration from API (86087f1a)
> dev-registration from API (86087f1a)

- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
dev-registration from API (eb08f728)
> dev-registration from API (eb08f728)

- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (68911849)

- libs/types/src/lib/api/Registration/checkIn.status.ts
- libs/types/src/lib/api/Registration/index.ts
- libs/types/src/lib/api/index.ts
> dev-vbl from API (3c74ad39)

- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (9d4b3140)

- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (3e47a0a7)

- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (8d8f8f7e)

- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (d8c8b27b)

- libs/types/src/lib/api/Identity/identity.view.ts
- libs/types/src/lib/api/Identity/index.ts
- libs/types/src/lib/api/Match/listUpcomingMatchesForUserSearchRequest.data.ts
- libs/types/src/lib/api/Statistic/groupedStatisticList.view.ts
- libs/types/src/lib/api/Statistic/index.ts
- libs/types/src/lib/api/Statistic/statisticList.view.ts
- libs/types/src/lib/api/Statistic/statisticValue.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
dev-statistic-requests from API (bc37448e)
> dev-statistic-requests from API (bc37448e)

- .changeset/witty-poets-share.md
- libs/core/src/lib/utils/scrollable.utils.ts
Option to add Scroll-Inline-Margin or Scroll-Block-Margin to scrollable.utils
> refactor: 💡 Add option for scrollmargin in scrollable

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (407029d0)

- libs/types/src/lib/api/Participant/participantList.view.ts
dev-postpone-tournament-schedule from API (7309f571)
> dev-postpone-tournament-schedule from API (7309f571)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (3734754d)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (7c722bb7)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (073d0d6d)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (e3e01445)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (2a55b333)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (813413ac)

- libs/types/src/lib/api/Participant/participantList.view.ts
> master from API (a5ebb2ae)

- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (af8548b9)

- libs/types/src/lib/api/Match/Stream/matchListWithStream.view.ts
- libs/types/src/lib/api/Match/detailedMatchList.view.ts
- libs/types/src/lib/api/Match/index.ts
- libs/types/src/lib/api/Match/matchListView.union.ts
- libs/types/src/lib/api/Round/Match/roundStageStructureWithMatches.view.ts
- libs/types/src/lib/api/Round/Match/roundWithMatches.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/Tournament/listSearchRequest.data.ts
- libs/types/src/lib/api/index.ts
> master from API (c8341266)

- libs/types/src/lib/api/Lineup/formationStructure.view.ts
- libs/types/src/lib/api/Lineup/index.ts
- libs/types/src/lib/api/Lineup/lineupList.view.ts
- libs/types/src/lib/api/Player/playerList.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
> master from API (052a5b5e)

- libs/types/src/lib/api/Round/index.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
> master from API (8acefb04)

- libs/types/src/lib/api/Group/groupList.view.ts
- libs/types/src/lib/api/Round/index.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
> master from API (2aa80907)

- .changeset/hot-drinks-develop.md
- libs/types/src/lib/api/Group/groupRanking.view.ts
- libs/types/src/lib/api/Player/playerList.view.ts
- libs/types/src/lib/api/Player/playerRoster.view.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
> master from API (48dd1b1b)

- libs/types/src/lib/api/Game/gameList.view.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
dev-vbl-new from API (8dd4e950)
> dev-vbl-new from API (8dd4e950)

- .changeset/config.json
- .changeset/poor-turkeys-shop.md
- libs/types/src/lib/api/Game/index.ts
- libs/types/src/lib/api/Game/lastXGamesByPlayer.view.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
dev-vbl-new from API (c3a556db)
> dev-vbl-new from API (c3a556db)

- libs/types/src/lib/api/Game/index.ts
- libs/types/src/lib/api/Game/lastXGamesByMatchGame.view.ts
- libs/types/src/lib/api/Media/media.view.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
dev-vbl-new from API (754663dc)
> dev-vbl-new from API (754663dc)

- libs/types/src/lib/api/Lineup/index.ts
- libs/types/src/lib/api/Lineup/lineupPlayerV.view.ts
- libs/types/src/lib/api/Overall/index.ts
- libs/types/src/lib/api/Overall/statisticOverallTournament.view.ts
- libs/types/src/lib/api/Overall/statisticOverallUtCardResults.view.ts
- libs/types/src/lib/api/Round/roundWithStageAndGroup.view.ts
- libs/types/src/lib/api/Statistic/statisticValue.view.ts
- libs/types/src/lib/api/Tournament/Registration/userTournamentRegistration.view.ts
- libs/types/src/lib/api/index.ts
dev-vbl-statistic from API (e4620b25)
> dev-vbl-statistic from API (e4620b25)

- .changeset/silver-pans-ring.md
- .changeset/thirty-ways-give.md
- libs/query/CHANGELOG.md
- libs/query/package.json
This reverts commit 8803ecbbdb3321df1efbbc5809b056c8828cdf67.
> Revert "chore: 🤖 update versions (#1602)"

- .changeset/beige-ravens-enjoy.md
- .changeset/gorgeous-seahorses-ring.md
- .changeset/lazy-apes-begin.md
- libs/cdk/src/lib/components/scrollable/components/scrollable/scrollable.component.html
- libs/cdk/src/lib/components/scrollable/components/scrollable/scrollable.component.scss
- libs/cdk/src/lib/components/scrollable/components/scrollable/scrollable.component.ts
- libs/cdk/src/lib/components/scrollable/stories/components/scrollable-storybook.component.ts
- libs/cdk/src/lib/components/scrollable/stories/scrollable.stories.ts
- libs/core/src/lib/utils/intersection-observer.utils.ts
Scrollable changes:
RenderNavigationWithButtons to render buttons in navigation
ScrollToCenter to set Origin to center
> Add renderNavigationWithButtons and scrollToCenter

- .changeset/tender-tires-deny.md
- libs/cdk/src/lib/components/forms/components/slider/components/slider/slider.component.html
- libs/cdk/src/lib/components/forms/components/slider/components/slider/slider.component.ts
- libs/cdk/src/lib/components/forms/components/slider/directives/slider-thumb-content-template/index.ts
- libs/cdk/src/lib/components/forms/components/slider/directives/slider-thumb-content-template/slider-thumb-content-template.directive.ts
- libs/cdk/src/lib/components/forms/components/slider/slider.imports.ts
- libs/cdk/src/lib/components/forms/components/slider/stories/components/slider-storybook.component.ts
Add template directive and outlet to display additional content in thumb container
> Add template directive and outlet to display additional content

- .changeset/brave-taxis-kiss.md
- libs/query/src/lib/experimental/http/query-snapshot.ts
> include execution state in createQuerySnapshot

- .changeset/wet-mails-smash.md
- libs/cdk/src/lib/components/forms/components/input/components/time-input/time-input.component.html
Time input gets min and max attribute
> Add min and max attributes to time-input
